questions =  [
  
//Economic Regulation - Planned
{"id": 0, "question": "In the current system, it is necessary for the government to intervene in the economy to protect consumers.", "effects": {"y": -2, "ay": 2}},
{"id": 1, "question": "Without state intervention, monopolies would violate human rights.", "effects": {"y": -2, "ay": -2}},
{"id": 2, "question": "Private organisations and corporations cannot be trusted and thus need regulating by the government.", "effects": {"x": -2, "ax": -2}},
{"id": 3, "question": "Governments should penalise businesses that mislead the public.", "effects": {"x": -2, "ax": -2}},
{"id": 4, "question": "Only the government can fairly and effectively regulate organisations.", "effects": {"x": -2, "ax": -2}},
{"id": 5, "question": "A genuine free market requires restrictions on the ability of predator multinationals to create monopolies.", "effects": {"x": -2, "ax": -2}},
{"id": 6, "question": "Environmental regulations are essential.", "effects": {"x": -2, "ax": -2}},  
//Economic Regulation - Laissez Faire
{"id": 7, "question": "Most corporations should be state-owned.", "effects": {"y": -2, "ay": 2}},
{"id": 8, "question": "A free economy is the best tool for establishing wages and the price of labour.", "effects": {"y": -2, "ay": -2}},
{"id": 9, "question": "The market regulates itself, unjust monopolies will not survive in a free market.", "effects": {"y": -2, "ay": -2}},
{"id": 10, "question": "A regulated economy is more unfair for the people, when compared to a laissez-faire economy.", "effects": {"y": -2, "ay": -2}},
{"id": 11, "question": "Taxation for the rich should be lowered, or even abolished.", "effects": {"y": -2, "ay": -2}},
{"id": 12, "question": "Government intervention is a threat to the economy.", "effects": {"y": -2, "ay": -2}},
{"id": 13, "question": "The government should not break up monopolies", "effects": {"y": -2, "ay": -2}},
{"id": 14, "question": "The government should not regulate the economy at all", "effects": {"y": -2, "ay": -2}},
  
//Economic System - Capitalism
{"id": 15, "question": "Communism is an ideology that would never work in practice.", "effects": {"y": 2, "ay": 2}},
{"id": 16, "question": "Economies without any capitalism will collapse", "effects": {"y": 2, "ay": 2}},
{"id": 17, "question": "Government owned industry is usually a bad idea", "effects": {"y": 2, "ay": 2}},
{"id": 18, "question": "Freedom of business is the best practical way a society can prosper.", "effects": {"x": 2, "ax": 2}},
{"id": 19, "question": "Governmental social programs should be replaced with private charities and organizations.", "effects": {"x": 2, "ax": 2}},
{"id": 20, "question": "It is better to maintain a balanced budget than to ensure welfare for all citizens.", "effects": {"x": 2, "ax": 2}},
{"id": 21, "question": "If wages exist at all, the minimum wage should be lowered or stagnated, or even abolished.", "effects": {"x": 2, "ax": 2}},
{"id": 22, "question": "The market should be able to provide a majority of healthcare services.", "effects": {"x": 2, "ax": 2}},
{"id": 23, "question": "Taxing citizens using involuntary methods can be considered an act of theft or agression.", "effects": {"x": 2, "ax": 2}},
{"id": 24, "question": "The Justice System should be partially privatized, or even fully privatized.", "effects": {"x": 2, "ax": 2}},
{"id": 25, "question": "Capitalism is the most practical and realistic economic system yet.", "effects": {"x": 2, "ax": 2}},
{"id": 26, "question": "Inheritance is a legitimate form of wealth.", "effects": {"x": 2, "ax": 2}},
{"id": 27, "question": "The harder you work, the more you progress up the social ladder.", "effects": {"x": 2, "ax": 2}},
{"id": 28, "question": "Controlling inflation is more important than controlling unemployment.", "effects": {"x": 2, "ax": 2}},
{"id": 29, "question": "Wages are always fair, as employers know best what a worker's labour is worth.", "effects": {"x": 2, "ax": 2}},
{"id": 30, "question": "It is human nature to be greedy.", "effects": {"x": 2, "ax": 2}},
{"id": 31, "question": "Exploitation is an outdated term, as the struggles of 1800s capitalism doesn't exist anymore.", "effects": {"x": 2, "ax": 2}},
{"id": 32, "question": "The only social responsibility of a company should be to deliver a profit to its shareholders.", "effects": {"x": 2, "ax": 2}},  
{"id": 33, "question": "What’s good for the most successful corporations is always, ultimately, good for all of us.", "effects": {"x": 2, "ax": 2}},  
{"id": 34, "question": "International trade is generally beneficial.", "effects": {"x": 2, "ax": 2}},  
{"id": 35, "question": "Borders only get in the way of international trade.", "effects": {"x": 2, "ax": 2}},  
{"id": 36, "question": "Businesses should compete worldwide.", "effects": {"x": 2, "ax": 2}},  
{"id": 37, "question": "Those who are able to work, and refuse the opportunity, should not expect society’s support.", "effects": {"x": 2, "ax": 2}},  
{"id": 38, "question": "People should have to work for anything they get", "effects": {"x": 2, "ax": 2}},  
{"id": 39, "question": "The poor choose to be poor", "effects": {"x": 2, "ax": 2}},  
{"id": 40, "question": "Those who do not work should die", "effects": {"x": 2, "ax": 2}},  
{"id": 41, "question": "Private Property should exist.", "effects": {"x": 2, "ax": 2}},  
{"id": 42, "question": "I should be able to control my own property.", "effects": {"x": 2, "ax": 2}},  
{"id": 43, "question": "All Property is Private.", "effects": {"x": 2, "ax": 2}},  
//Economic System - Socialism
{"id": 44, "question": "Communism, if implemented correctly, would be a good form of economics", "effects": {"x": -2, "ax": -2}},
{"id": 45, "question": "Taxes should be increased on the rich to provide for the poor.", "effects": {"x": -2, "ax": -2}},
{"id": 46, "question": "The wealthy have far more than they need", "effects": {"x": -2, "ax": -2}},
{"id": 47, "question": "People born to wealthy families have unfair success even when they aren't skilled and don't work hard", "effects": {"x": -2, "ax": -2}},
{"id": 48, "question": "From each according to their ability, to each according to their needs.", "effects": {"x": -2, "ax": -2}},
{"id": 49, "question": "Oppression by corporations is more of a concern than oppression by governments.", "effects": {"x": -2, "ax": -2}},
{"id": 50, "question": "The means of production should belong to the workers.", "effects": {"x": -2, "ax": -2}},
{"id": 51, "question": "Roads and transportation should be publicly owned.", "effects": {"x": -2, "ax": -2}},
{"id": 52, "question": "Economic inequality is still a very serious problem.", "effects": {"x": -2, "ax": -2}},
{"id": 53, "question": "Paying workers with food is preferable than paying with money.", "effects": {"x": -2, "ax": -2}},
{"id": 54, "question": "Currency is a baseless idea, that should not exist.", "effects": {"x": -2, "ax": -2}},
{"id": 55, "question": "The very existance of collectives are a spook.", "effects": {"x": -2, "ax": -2}},
{"id": 56, "question": "Land shouldn’t be a commodity to be bought and sold.", "effects": {"x": -2, "ax": -2}},
{"id": 57, "question": "It is regrettable that many personal fortunes are made by people who simply manipulate money and contribute nothing to their society.", "effects": {"x": -2, "ax": -2}},
{"id": 58, "question": "A government that provides for everyone is an inherently good idea.", "effects": {"x": -2, "ax": -2}},
{"id": 59, "question": "The current welfare system should be expanded to further combat inequality.", "effects": {"x": -2, "ax": -2}},
{"id": 60, "question": "All industry and the bank should be nationalised.", "effects": {"x": -2, "ax": -2}},  
{"id": 61, "question": "If economic globalisation is inevitable, it should primarily serve humanity rather than the interests of trans-national corporations.", "effects": {"x": -2, "ax": -2}},  
{"id": 62, "question": "It’s a sad reflection on our society that something as basic as drinking water is now a bottled, branded consumer product.", "effects": {"x": -2, "ax": -2}},    
{"id": 63, "question": "Multinational companies are unethically exploiting the plant genetic resources of developing countries.", "effects": {"x": -2, "ax": -2}},  
{"id": 64, "question": "Publicly-funded research is more beneficial to the people than leaving it to the market.", "effects": {"x": -2, "ax": -2}},  
{"id": 65, "question": "Tariffs on international trade are important to encourage local production.", "effects": {"x": -2, "ax": -2}}, 
{"id": 66, "question": "Protectionism is sometimes necessary in trade.", "effects": {"x": -2, "ax": -2}},
{"id": 67, "question": "Important things like Education and Healthcare should be public.", "effects": {"x": -2, "ax": -2}},
{"id": 68, "question": "The word Mine is offensive.", "effects": {"x": -2, "ax": -2}},

//Governmental System - Autocracy
{"id": 69, "question": "An autocracy is more beneficial than any democratic system.", "effects": {"y": 2, "bx": -2}},
{"id": 70, "question": "A beneficial democracy requires high levels of education.", "effects": {"y": 2, "bx": -2}},
{"id": 71, "question": "If the electoral college exists at all, electoral votes needs to be adjusted so that different states/regions get representation.", "effects": {"y": 2, "bx": -2}},
{"id": 72, "question": "Democracy increases the risks of instability and corruption.", "effects": {"y": 2, "bx": -2}},
{"id": 73, "question": "Democracy makes it too easy for a majority to further itself at the expense of minorities", "effects": {"y": 2, "bx": -2}},
{"id": 74, "question": "Only allowing scientific experts to run for an election is preferable than that of a regular democracy.", "effects": {"y": 2, "bx": -2}},
{"id": 75, "question": "A significant advantage of a one-party state is that it avoids all the arguments that delay progress in a democratic political system.", "effects": {"y": 2, "bx": -2}},  
{"id": 76, "question": "The general populace makes poor decisions.", "effects": {"y": 2, "bx": -2}},
{"id": 77, "question": "Theocracy is a good system of government", "effects": {"y": 2, "bx": -2}},
{"id": 78, "question": "Public opinion swings too much with emotional events to be useful for policy making", "effects": {"y": 2, "bx": -2}},
{"id": 79, "question": "Popular opinion is not always right", "effects": {"y": 2, "bx": -2}},
{"id": 80, "question": "Catering to popular opinion is detrimental to a nation", "effects": {"y": 2, "bx": -2}},
{"id": 81, "question": "Elections are a waste of resources", "effects": {"y": 2, "bx": -2}},
{"id": 82, "question": "Only those who serve in the military should be allowed to have influence on who is in power", "effects": {"y": 2, "by": 2}}, 
{"id": 83, "question": "Democracy is the worst form of government, except for all the others we've tried.", "effects": {"y": 2, "by": 2}}, 
{"id": 84, "question": "Democratic systems are unstable, and dangerous.", "effects": {"y": 2, "by": 2}}, 
{"id": 85, "question": "Some people are more fit to rule than others, thus they should.", "effects": {"y": 2, "by": 2}}, 
{"id": 86, "question": "An upper class of people have gained their status for a reason, they are by all definitions more fit to rule than lower classmen.", "effects": {"y": 2, "by": 2}}, 
//Governmental System - Democracy
{"id": 87, "question": "Liberal democracy is the least worst system for leadership.", "effects": {"y": -2, "bx": 2}},
{"id": 88, "question": "Without democracy, a society is nothing.", "effects": {"y": -2, "bx": 2}},
{"id": 89, "question": "Democracy is more than a decision-making process.", "effects": {"y": -2, "bx": 2}},
{"id": 90, "question": "Direct democracy is the best form of government", "effects": {"y": -2, "bx": 2}},
{"id": 91, "question": "The Majority knows what is best for the nation.", "effects": {"y": -2, "bx": 2}},
{"id": 92, "question": "The Minority does not matter, the Majority is far more important.", "effects": {"y": -2, "bx": 2}},
{"id": 93, "question": "It is important that the government follows the majority opinion, even if it is wrong.", "effects": {"y": -2, "bx": 2}},
{"id": 94, "question": "If the Majority likes an idea, it should be implemented no matter how destructive it is.", "effects": {"y": -2, "bx": 2}},
{"id": 95, "question": "Each person should have one vote, each equal to every other", "effects": {"y": -2, "bx": 2}},
{"id": 96, "question": "The more people asked, the better chance there is of reaching the best decision.", "effects": {"y": -2, "bx": 2}},
{"id": 97, "question": "Elections are an effective way of showing government approval", "effects": {"y": -2, "bx": 2}},
{"id": 98, "question": "People should have the power to choose their leaders", "effects": {"y": -2, "bx": 2}},
{"id": 99, "question": "People should vote issue by issue themselves", "effects": {"y": -2, "bx": 2}},
{"id": 100, "question": "People know how to rule better than the Higher-Class.", "effects": {"y": -2, "bx": 2}},
{"id": 101, "question": "No one but the people can make good decisions, and the more people who are deciding, the better.", "effects": {"y": -2, "bx": 2}},

//Governmental Size - Authoritarian
{"id": 102, "question": "Violence is not acceptable no matter the circumstances.", "effects": {"y": 2, "by": 2}},
{"id": 103, "question": "The sacrifice of some civil liberties is necessary to protect us from acts of terrorism.", "effects": {"y": 2, "by": 2}},
{"id": 104, "question": "When a threat arrives, some liberties should be sacrificed in order to maintain stability and prosperity.", "effects": {"y": 2, "by": 2}},
{"id": 105, "question": "Some freedom must be given up in order to keep people safe", "effects": {"y": 2, "by": 2}},
{"id": 106, "question": "Strength and substantial authority is required for a successful and efficient government.", "effects": {"y": 2, "by": 2}},
{"id": 107, "question": "Many problems in society are often solved quickly and easily by a large government.", "effects": {"y": 2, "by": 2}},
{"id": 108, "question": "If you have nothing to hide, then you shouldn't care about the government having access to your communications", "effects": {"y": 2, "by": 2}},
{"id": 109, "question": "Martial law is appropiate if a nation is undergoing a crisis.", "effects": {"y": 2, "by": 2}},
{"id": 110, "question": "Mandatory IDs should be used to ensure public safety.", "effects": {"y": 2, "by": 2}},  
{"id": 111, "question": "The government should, at most, provide emergency services and law enforcement.", "effects": {"y": 2, "by": 2}},  
{"id": 112, "question": "Government surveillance is necessary in the modern world.", "effects": {"y": 2, "by": 2}},  
{"id": 113, "question": "Although the electronic age makes official surveillance easier, only wrongdoers need to be worried.", "effects": {"y": 2, "by": 2}},
{"id": 114, "question": "People should not have protections that could hinder discovering their criminal activity", "effects": {"y": 2, "by": 2}},
{"id": 115, "question": "The government should monitor all citizens to combat terrorism", "effects": {"y": 2, "by": 2}},
{"id": 116, "question": "The government should have access to the emails of suspected terrorists", "effects": {"y": 2, "by": 2}},
{"id": 117, "question": "Making peace with the establishment is an important aspect of maturity.", "effects": {"y": 2, "by": 2}},  
{"id": 118, "question": "Military action by our nation is often necessary to protect it.", "effects": {"y": 2, "by": 2}},  
{"id": 119, "question": "The stronger the leadership, the better.", "effects": {"y": 2, "by": 2}},  
{"id": 120, "question": "Leaders must be strong or a nation will suffer", "effects": {"y": 2, "by": 2}},  
{"id": 121, "question": "If a leader is put into power, he should not be restricted by any means.", "effects": {"y": 2, "by": 2}},  
{"id": 122, "question": "Society could not function without leaders and followers", "effects": {"y": 2, "by": 2}},  
{"id": 123, "question": "Abortion should be prohibited in most or all cases.", "effects": {"y": 2, "by": 2}},  
{"id": 124, "question": "Gun ownership should be prohibited for those without a valid reason.", "effects": {"y": 2, "by": 2}},  
{"id": 125, "question": "Prostitution should be illegal.", "effects": {"y": 2, "by": 2}},  
{"id": 126, "question": "The national government protects minorities better than some local governments do.", "effects": {"y": 2, "by": 2}}, 
{"id": 127, "question": "The national government needs more power", "effects": {"y": 2, "by": 2}}, 
{"id": 128, "question": "States cannot function without a strong national government", "effects": {"y": 2, "by": 2}}, 
{"id": 129, "question": "Strong states weaken a nation", "effects": {"y": 2, "by": 2}},  
{"id": 130, "question": "Subdivisions should not be able to exempt from national laws", "effects": {"y": 2, "by": 2}},
{"id": 131, "question": "Laws should be completely consistent within all regions of a nation", "effects": {"y": 2, "by": 2}},
{"id": 132, "question": "A country must be sure to take all measures to enforce its laws", "effects": {"y": 2, "by": 2}},
{"id": 133, "question": "A national government must be strong to adequately protect all its citizens", "effects": {"y": 2, "by": 2}}, 
{"id": 134, "question": "People should think of themselves as citizens of their nation rather than their state", "effects": {"y": 2, "by": 2}}, 
{"id": 135, "question": "Absolute freedom makes a society dangerous", "effects": {"y": 2, "by": 2}}, 
{"id": 136, "question": "There are many issues that it does not make sense to address at a local level", "effects": {"y": 2, "by": 2}},  
{"id": 137, "question": "Those who disagree with the government should be removed from the country", "effects": {"y": 2, "by": 2}},  
{"id": 138, "question": "I wouldn't care if people died at large amounts if they are not related to me.", "effects": {"y": 2, "by": 2}}, 
{"id": 139, "question": "I would not feel anything I were to murder an entire family of innocent people. (You won't get punished)", "effects": {"y": 2, "by": 2}}, 
{"id": 140, "question": "A nation must obey its leadership without question", "effects": {"y": 2, "by": 2}},
{"id": 141, "question": "The government should support and only recognize one religion", "effects": {"y": 2, "by": 2}},  
{"id": 142, "question": "Religious clothing should be banned from public", "effects": {"y": 2, "by": 2}},  
{"id": 143, "question": "Religion should be banned", "effects": {"y": 2, "by": 2}},  
{"id": 144, "question": "The Internet should be banned", "effects": {"y": 2, "by": 2}},  
{"id": 145, "question": "Any type of Hate speech based on an individual's gender, race, religon, sexual orientation, or gender indentity should be banned.", "effects": {"y": 2, "by": 2}},  
{"id": 146, "question": "A nation usually needs a military in order to survive", "effects": {"y": 2, "by": 2}},
{"id": 147, "question": "A government must maintain a strong military to defend itself", "effects": {"y": 2, "by": 2}},
{"id": 148, "question": "There should be compulsory military service", "effects": {"y": 2, "by": 2}}, 
{"id": 149, "question": "We should respect those who have served in our military", "effects": {"y": 2, "by": 2}},
{"id": 150, "question": "A military option should always be considered", "effects": {"y": 2, "by": 2}},
{"id": 151, "question": "A constant state of war benefits a country", "effects": {"y": 2, "by": 2}},  
{"id": 152, "question": "War is needed to make an economy thrive", "effects": {"y": 2, "by": 2}},
{"id": 153, "question": "War is the answer to every single problem we can imagine, no matter how small or insignificant.", "effects": {"y": 2, "by": 2}},
{"id": 154, "question": "War is necessary, and will always exist as long as there are people around.", "effects": {"y": 2, "by": 2}},
{"id": 155, "question": "Nukes should be used in every war, even small wars and wars on terror.", "effects": {"y": 2, "by": 2}},
{"id": 156, "question": "JUST NUKE EVERYTHING!!!", "effects": {"y": 2, "by": 2}},
{"id": 157, "question": "Diplomacy only hurts nations", "effects": {"y": 2, "by": 2}},  
{"id": 158, "question": "Police need more power and protection", "effects": {"y": 2, "by": 2}},  
//Governmental Size - Libertarian
{"id": 159, "question": "Any action that does not impose agression on any person should not be considered a criminal offence.", "effects": {"y": -2, "by": -2}},
{"id": 160, "question": "All authority should be questioned.", "effects": {"y": -2, "by": -2}},
{"id": 161, "question": "The existence of the state is a violation of our liberty and rights.", "effects": {"y": -2, "by": -2}},
{"id": 162, "question": "Any drug should be legal as long as other people don't have to take the consequences.", "effects": {"y": -2, "by": -2}},
{"id": 163, "question": "Whether or not the state is democratic, it is still oppresive.", "effects": {"y": -2, "by": -2}},
{"id": 164, "question": "Environmental activism and social pressure are a more effective way of saving the environment when compared to government action.", "effects": {"y": -2, "by": -2}},
{"id": 165, "question": "Governments should stay out of the people's daily lives.", "effects": {"y": -2, "by": -2}},
{"id": 166, "question": "The police was not made to protect the people, but to uphold the status-quo by force.", "effects": {"y": -2, "by": -2}},
{"id": 167, "question": "Police should be regulated more", "effects": {"y": -2, "by": -2}},
{"id": 168, "question": "Victimless crimes should not be considered 'crimes'.", "effects": {"y": -2, "by": -2}},
{"id": 169, "question": "Jury nullification should be legal.", "effects": {"y": -2, "by": -2}},
{"id": 170, "question": "State schools are a bad idea because our state shouldn't be influencing our children.", "effects": {"y": -2, "by": -2}}, 
{"id": 171, "question": "Pornography, depicting consenting adults, should be legal for the adult population.", "effects": {"y": -2, "by": -2}}, 
{"id": 172, "question": "Physician-assisted suicide should be legal.", "effects": {"y": -2, "by": -2}}, 
{"id": 173, "question": "Same-sex marriage should be legal.", "effects": {"y": -2, "by": -2}}, 
{"id": 174, "question": "What goes on in a private bedroom between consenting adults is no business of the state.", "effects": {"y": -2, "by": -2}}, 
{"id": 175, "question": "It is more important to retain peaceful relations than to further our strength.", "effects": {"y": -2, "by": -2}}, 
{"id": 176, "question": "Wars do not need to be justified to other countries.", "effects": {"y": -2, "by": -2}}, 
{"id": 177, "question": "Peace is preferable to war whenever possible", "effects": {"y": -2, "by": -2}}, 
{"id": 178, "question": "Countries fall apart with constant war", "effects": {"y": -2, "by": -2}}, 
{"id": 179, "question": "War usually leads to worse outcomes", "effects": {"y": -2, "by": -2}}, 
{"id": 180, "question": "Diplomatic options should always be tried before war is even considered", "effects": {"y": -2, "by": -2}}, 
{"id": 181, "question": "Lasting peace leads to prosperity", "effects": {"y": -2, "by": -2}}, 
{"id": 182, "question": "Nukes are not acceptable, and should all be destroyed.", "effects": {"y": -2, "by": -2}}, 
{"id": 183, "question": "State laws should have precedence over national laws", "effects": {"y": -2, "by": -2}}, 
{"id": 184, "question": "There is no need for local or state governments", "effects": {"y": -2, "by": -2}}, 
{"id": 185, "question": "In the modern era, militaries aren't really necessary", "effects": {"y": -2, "by": -2}}, 
{"id": 186, "question": "People should hold more loyalty to their local state than their country.", "effects": {"y": -2, "by": -2}}, 
{"id": 187, "question": "Schools should not make classroom attendance compulsory", "effects": {"y": -2, "by": -2}}, 
{"id": 188, "question": "People should be given freedom whenever it causes little security risk", "effects": {"y": -2, "by": -2}}, 
{"id": 189, "question": "Laws should vary from area to area and culture to culture within a country.", "effects": {"y": -2, "by": -2}}, 
{"id": 190, "question": "Local governments give each region good representation of their views", "effects": {"y": -2, "by": -2}},
{"id": 191, "question": "Local governments address issues that the national government would never touch without them", "effects": {"y": -2, "by": -2}},
{"id": 192, "question": "Local governments should have more power than they currently do", "effects": {"y": -2, "by": -2}},
{"id": 193, "question": "Federal Governments are much more stable than Unitary ones.", "effects": {"y": -2, "by": -2}},
{"id": 194, "question": "Small communes are much more effective at governing themselves than central governments.", "effects": {"y": -2, "by": -2}},
{"id": 195, "question": "A City/Commune is more stable than a Nation.", "effects": {"y": -2, "by": -2}},
{"id": 196, "question": "Everyone gets what they want in an Urbanist Society.", "effects": {"y": -2, "by": -2}},
{"id": 197, "question": "The government must be by the people for the people", "effects": {"y": -2, "by": -2}},
{"id": 198, "question": "Subdivisions of nations should have their own militaries", "effects": {"y": -2, "by": -2}}, 
{"id": 199, "question": "It's a good idea to test a policy in one state rather than implementing it nationwide right away", "effects": {"y": -2, "by": -2}}, 
{"id": 200, "question": "There is no need for a national government", "effects": {"y": -2, "by": -2}}, 
{"id": 201, "question": "A group of states without a strong national government is merely an alliance, not a nation", "effects": {"y": 2, "by": 2}},
{"id": 202, "question": "There should be no police force", "effects": {"y": -2, "by": -2}}, 
{"id": 203, "question": "People's freedom should have no limits", "effects": {"y": -2, "by": -2}}, 
{"id": 204, "question": "Abortion should be legal in all cases", "effects": {"y": -2, "by": -2}}, 
{"id": 205, "question": "People must be allowed to follow a religion", "effects": {"y": -2, "by": -2}}, 
{"id": 206, "question": "Religious organizations often provide better assistance to the poor than the government does", "effects": {"y": -2, "by": -2}},
{"id": 207, "question": "Nations should not maintain a military", "effects": {"y": -2, "by": -2}}, 
{"id": 208, "question": "Whistleblowers should be strongly protected", "effects": {"y": -2, "by": -2}}, 
{"id": 209, "question": "There should not be a leader in society.", "effects": {"y": -2, "by": -2}}, 

//Diplomatic Applicability - Universal
{"id": 210, "question": "My political values should be spread as much as possible.", "effects": {"cx": -2}},
{"id": 211, "question": "Countries with authoritarian governments should be denounced.", "effects": {"cx": -2}},
{"id": 212, "question": "Globalization is inevitable.", "effects": {"cx": -2}},
{"id": 213, "question": "Cultures should learn from each others to make progress quicker and easier.", "effects": {"cx": -2}},
{"id": 214, "question": "Violent action should be made to countries that violate basic human rights.", "effects": {"cx": -2}},
//Diplomatic Applicability - Particular
{"id": 215, "question": "Different countries and cultures have different preferences for the type of government.", "effects": {"cx": 2}},
{"id": 216, "question": "All countries should solve its internal issues before focusing on external issues.", "effects": {"cx": 2}},
{"id": 217, "question": "Conflict should be avoided as much as possible.", "effects": {"cx": 2}},

//Diplomatic Relations - Nationalism
{"id": 218, "question": "If I were to support international organizations at all, I will only support international organizations that align with my political beliefs.", "effects": {"cy": 2}},
{"id": 219, "question": "My nation's interests should be considered more important than that of other nations.", "effects": {"cy": 2}},
{"id": 220, "question": "National sovereignty is very important.", "effects": {"cy": 2}},
{"id": 221, "question": "It's a good thing that Nationalism is on the rise.", "effects": {"cy": 2}},
{"id": 222, "question": "If a certain group has a very strong group identity, an independence referendum should be held.", "effects": {"cy": 2}},
{"id": 223, "question": "Each nation should govern itself with minimal or no foreign intervention.", "effects": {"cy": 2}},
{"id": 224, "question": "The United Nations should be abolished.", "effects": {"cy": 2}},
{"id": 225, "question": "My nation is great.", "effects": {"cy": 2}},
{"id": 226, "question": "Our nation's values should be spread as much as possible.", "effects": {"cy": 2}},
{"id": 227, "question": "Regardless of political opinions, it is important to side with your country.", "effects": {"cy": 2}},
{"id": 228, "question": "It is important that we further my group's goals above all others.", "effects": {"cy": 2}},
{"id": 229, "question": "Alliances can pose a threat to a nation's sovereignty.", "effects": {"cy": 2}},
{"id": 230, "question": "My nation should stay out of international affairs", "effects": {"cy": 2}},
{"id": 231, "question": "My nation is closer to my views than most nations in the world", "effects": {"cy": 2}},
{"id": 232, "question": "Nobody in other countries has our best interests in mind", "effects": {"cy": 2}},
{"id": 233, "question": "Representatives rarely represent the nation well", "effects": {"cy": 2}},
{"id": 234, "question": "I don't want to get related to outsiders.", "effects": {"cy": 2}},
{"id": 235, "question": "Only extremely talented immigrants, if that, should be permitted to enter the country", "effects": {"cy": 2}},
{"id": 236, "question": "Immigrants should be expected to learn the language of the country", "effects": {"cy": 2}},
{"id": 237, "question": "Only our national language(s) should be spoken in our country", "effects": {"cy": 2}},
{"id": 238, "question": "Foreigners should never enter the country", "effects": {"cy": 2}},
{"id": 239, "question": "We should not allow any refugees", "effects": {"cy": 2}},
{"id": 240, "question": "In general, immigrants are bad for the country", "effects": {"cy": 2}},
{"id": 241, "question": "Illegal immigrants should be deported in most or all cases", "effects": {"cy": 2}},
{"id": 242, "question": "The benefits of open borders would outweigh the costs", "effects": {"cy": 2}},
{"id": 243, "question": "Border protection is important", "effects": {"cy": 2}},
{"id": 244, "question": "International aid is a waste of money.", "effects": {"cy": 2}},
{"id": 245, "question": "My people deserve better than what the international world offers us.", "effects": {"cy": 2}},
{"id": 246, "question": "There should be no International Law/War Crimes.", "effects": {"cy": 2}},
{"id": 247, "question": "I’d always support my country, whether it was right or wrong.", "effects": {"cy": 2}},
{"id": 248, "question": "Any deals other countries want must be bad for us", "effects": {"cy": 2}},
{"id": 249, "question": "It would be best if the outside world didn't know about my people or country.", "effects": {"cy": 2}},
{"id": 250, "question": "There should be no immigration, foreign affairs, contact, or knowledge of my nation.", "effects": {"cy": 2}},
{"id": 251, "question": "There should not be international law", "effects": {"cy": 2}},
{"id": 252, "question": "Our race has many superior qualities, compared with other races.", "effects": {"cy": 2}},  
{"id": 253, "question": "We have no right to militarily intervene in other nations", "effects": {"cy": 2}},  
//Diplomatic Relations - Globalism
{"id": 254, "question": "No one chooses their country of birth, so it’s foolish to be proud of it.", "effects": {"cy": -2}},
{"id": 255, "question": "We should open our borders to immigration.", "effects": {"cy": -2}},
{"id": 256, "question": "Governments should be as concerned about foreigners as they are about their own citizens.", "effects": {"cy": -2}},
{"id": 257, "question": "We should be taking in more refugees", "effects": {"cy": -2}},
{"id": 258, "question": "A global nation where all countries are united will be beneficial to humanity.", "effects": {"cy": -2}},
{"id": 259, "question": "A global organization that is generally beneficial should hold a substantial amount of power.", "effects": {"cy": -2}},
{"id": 260, "question": "There should be a one world government.", "effects": {"cy": -2}},
{"id": 261, "question": "A single, Intergalactic Space-Empire is something we should strive for.", "effects": {"cy": -2}},
{"id": 262, "question": "If there are other intelligent species somewhere in the universe, we should aim to join our forces and make one, unitary, Inter-Galactic Super-Empire.", "effects": {"cy": -2}},
{"id": 263, "question": "I support Regional Unions, like the European Union.", "effects": {"cy": -2}},
{"id": 264, "question": "The United Nations needs more power", "effects": {"cy": -2}},
{"id": 265, "question": "The United Nations should have a military to enforce its resolutions", "effects": {"cy": -2}},
{"id": 266, "question": "Nations should cooperate whenever it benefits them both", "effects": {"cy": -2}},
{"id": 267, "question": "Alliances are important for protecting a nation", "effects": {"cy": -2}},
{"id": 268, "question": "It's important that we put aside our differences and cooperate as a single community.", "effects": {"cy": -2}},
{"id": 269, "question": "Our country should aim to improve relations with other nations, and conduct foreign affairs regularly.", "effects": {"cy": -2}},
{"id": 270, "question": "All foreign affairs are good.", "effects": {"cy": -2}},
{"id": 271, "question": "Having independent nations with the risk of global conflict creates a large threat to humanity as a whole", "effects": {"cy": -2}},
{"id": 272, "question": "Governments should be accountable to the international community.", "effects": {"cy": -2}},
{"id": 273, "question": "Military spending is a waste of money.", "effects": {"cy": -2}},
{"id": 274, "question": "Borders around the world should be less strict.", "effects": {"cy": -2}},
{"id": 275, "question": "In order for humanity to survive, we must get past having separate nations", "effects": {"cy": -2}},
{"id": 276, "question": "Immigrants are a net positive", "effects": {"cy": -2}},
{"id": 277, "question": "Anybody who wants to enter the country should be able to", "effects": {"cy": -2}},
{"id": 278, "question": "Research should be conducted on an international scale.", "effects": {"cy": -2}},
{"id": 279, "question": "All humans share a common identity", "effects": {"cy": -2}},
{"id": 280, "question": "We are first and foremost citizens of Earth", "effects": {"cy": -2}},
  
//Societal Tradition - Tradition
{"id": 281, "question": "It's important that we maintain our culture and tradition.", "effects": {"dx": 2}},
{"id": 282, "question": "Tradition is vital for society.", "effects": {"dx": 2}},
{"id": 283, "question": "All traditions deserve the same amount of respect.", "effects": {"dx": 2}},
{"id": 284, "question": "Anything, including murder and rape, are acceptable as long as they're cultural traditions.", "effects": {"dx": 2}},
{"id": 285, "question": "Maintaining family values is essential.", "effects": {"dx": 2}},
{"id": 286, "question": "Religion is beneficial for society", "effects": {"dx": 2}},
{"id": 287, "question": "One cannot truly live without faith.", "effects": {"dx": 2}},
{"id": 288, "question": "My religious values should be spread as much as possible.", "effects": {"dx": 2}},
{"id": 289, "question": "My Political ideas are influenced by my Religion.", "effects": {"dx": 2}},
{"id": 290, "question": "My Political ideas were influenced by my God, and were meant for me to spread them.", "effects": {"dx": 2}},
{"id": 291, "question": "Most bad things happening in the world are caused by us turning away from religion", "effects": {"dx": 2}},
{"id": 292, "question": "Sacrifices are good as long as they're for some divine or mystical being.", "effects": {"dx": 2}},
{"id": 293, "question": "Without a Divine Being, there is nothing.", "effects": {"dx": 2}},
{"id": 294, "question": "To chase progress at all costs is dangerous.", "effects": {"dx": 2}},
{"id": 295, "question": "There is now a worrying fusion of information and entertainment.", "effects": {"dx": 2}},
{"id": 296, "question": "I consider abortion as a form of murder.", "effects": {"dx": 2}},
{"id": 297, "question": "Transgender individuals should not be able to adopt children.", "effects": {"dx": 2}}, 
{"id": 298, "question": "No one can feel naturally homosexual.", "effects": {"dx": 2}}, 
{"id": 299, "question": "Traditional medicines are often more effective than modern medicines.", "effects": {"dx": 2}},
{"id": 300, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"dx": -2}}, 
{"id": 301, "question": "The elders in society know the best path for it", "effects": {"dx": -2}}, 
{"id": 302, "question": "A person cannot be moral without a religion or belief.", "effects": {"dx": -2}},
{"id": 303, "question": "Children should be educated in religious or traditional values.", "effects": {"dx": -2}},
{"id": 304, "question": "Religion should play a role in government.", "effects": {"dx": -2}},
{"id": 305, "question": "Astrology accurately explains many things.", "effects": {"dx": -2}},
{"id": 306, "question": "Religion usually provides the truth", "effects": {"dx": -2}},
{"id": 307, "question": "I believe in a higher power", "effects": {"dx": -2}},
{"id": 308, "question": "I believe there is something after death", "effects": {"dx": -2}},
{"id": 309, "question": "Mothers may have careers, but their first duty is to be homemakers.", "effects": {"dx": -2}},
{"id": 310, "question": "Sex outside marriage is usually immoral.", "effects": {"dx": -2}},
{"id": 311, "question": "These days openness about sex has gone too far.", "effects": {"dx": -2}},
//Societal Tradition - Progress
{"id": 312, "question": "Religion is mostly fictional.", "effects": {"dx": -2}}, 
{"id": 313, "question": "There is no higher power", "effects": {"dx": -2}}, 
{"id": 314, "question": "A person should be able to worship whomever or whatever they want.", "effects": {"dx": -2}},   
{"id": 315, "question": "Every religion must be looked upon equally by the government", "effects": {"dx": -2}},
{"id": 316, "question": "Religion should be removed from everything in our government", "effects": {"dx": -2}},
{"id": 317, "question": "The government should not fund any religious organizations in any way", "effects": {"dx": -2}},
{"id": 318, "question": "There must be a separation between church and state", "effects": {"dx": -2}},
{"id": 319, "question": "Religion must decline for society to progress", "effects": {"dx": -2}},
{"id": 320, "question": "Religions are dangerous, and slow down Humanity.", "effects": {"dx": -2}},
{"id": 321, "question": "Laws should not be based on religion", "effects": {"dx": -2}},
{"id": 322, "question": "Traditions are of no value on their own.", "effects": {"dx": -2}},
{"id": 323, "question": "Reason is more important than maintaining our culture.", "effects": {"dx": -2}},
{"id": 324, "question": "I support the LGBT Community.", "effects": {"dx": -2}},
{"id": 325, "question": "I support the Black Lives Matter organization.", "effects": {"dx": -2}},
{"id": 326, "question": "If taxation exists, churches should be taxed the same way other institutions are taxed.", "effects": {"dx": -2}},
{"id": 327, "question": "Evolution is a fact.", "effects": {"dx": -2}},
{"id": 328, "question": "Two consenting individuals should be able to do whatever they want with each other, even if it makes me uncomfortable.", "effects": {"dx": -2}},
{"id": 329, "question": "An individual's body is their own property, and they should be able to do anything they desire to it.", "effects": {"dx": -2}},
{"id": 330, "question": "Nudism is perfectly natural.", "effects": {"dx": -2}},
{"id": 331, "question": "Animals deserve certain universal rights.", "effects": {"dx": -2}},  
{"id": 332, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"dx": -2}},    
{"id": 333, "question": "Laws based on cultural values, rather than ethical ones, aren't justice.", "effects": {"dx": -2}},    
{"id": 334, "question": "Autonomy of body extends even to minors, the mentally ill, and serious criminals.", "effects": {"dx": -2}},     
{"id": 335, "question": "Climate change is currently one of the greatest threats to our way of life.", "effects": {"dx": -2}}, 
{"id": 336, "question": "It is important that we work as a united world to combat climate change.", "effects": {"dx": -2}}, 
{"id": 337, "question": "Nations fighting among each other gets in the way of progress", "effects": {"dx": -2}}, 
{"id": 338, "question": "Empires like the Roman Empire, were very effective and gave lots of progress to humanity.", "effects": {"dx": -2}}, 
//Societal Change - Conserve
{"id": 339, "question": "Rapid change often leads to the worsening of people's lives.", "effects": {"dy": 2}},
{"id": 340, "question": "Reforms should happen gradually and slowly.", "effects": {"dy": 2}},
{"id": 341, "question": "All reforms should happen without violence.", "effects": {"dy": 2}},
{"id": 342, "question": "It's sometimes moral to crush a revolution or protest by force.", "effects": {"dy": 2}},
{"id": 343, "question": "Political leaders should change the system as little as possible during their term.", "effects": {"dy": 2}}, 
//Societal Change - Reform
{"id": 344, "question": "Thinking in the long term is more important than thinking in the short term.", "effects": {"dy": -2}},
{"id": 345, "question": "The current political system in my nation is flawed.", "effects": {"dy": -2}},
{"id": 346, "question": "We should avoid delaying political reform and change.", "effects": {"dy": -2}},
{"id": 347, "question": "If the cause is justified in my political ideology and peaceful reform does not work, revolution and aggressive measures should be considered.", "effects": {"dy": -2}},

//Technological Acceleration - Decelerate
{"id": 348, "question": "Technology is negatively affecting modern society.", "effects": {"ex": -2}},
{"id": 349, "question": "The Industrial Revolution and its consequences have been a disaster for the human race.", "effects": {"ex": -2}},
{"id": 350, "question": "Usage of genetic modification for animals and plants should be minimized.", "effects": {"ex": -2}},
{"id": 351, "question": "Genetic modification should be used rarely, if ever", "effects": {"ex": -2}},
{"id": 352, "question": "We should preserve nature, rather than upgrading technology.", "effects": {"ex": -2}},
{"id": 353, "question": "Modernity and social progress has led to a decrease of happiness, and often lacks meaning.", "effects": {"ex": -2}},
{"id": 354,  "question": "Society was better many years ago than it is today.", "effects": {"ex": -2}}, 
{"id": 355,  "question": "Fully Sentient A.I is too dangerous and should not be invented.", "effects": {"ex": -2}}, 
//Technological Acceleration - Accelerate
{"id": 356, "question": "If artifical intellegence can rule better than humans, then they should rule.", "effects": {"ex": -2}},
{"id": 357, "question": "Genetic modification of food can avoid effects from droughts and floods.", "effects": {"ex": -2}},
{"id": 358, "question": "Automation is very beneficial for society.", "effects": {"ex": -2}},
{"id": 359, "question": "Genetic modification of humans is beneficial.", "effects": {"ex": -2}},
{"id": 360, "question": "Testing products on animals is ethical", "effects": {"ex": -2}},
{"id": 361, "question": "Societal progress is heading in the right direction.", "effects": {"ex": -2}},
{"id": 362, "question": "Technological progress is usually good", "effects": {"ex": -2}},
{"id": 363, "question": "We should embrace modern technology rather than avoiding it.", "effects": {"ex": -2}},
{"id": 364, "question": "Tradition just hinders the progress of technology.", "effects": {"ex": -2}},
{"id": 365, "question": "A better world will come from automation, science, and technology.", "effects": {"ex": -2}},
{"id": 366, "question": "Technology will solve all of our problems.", "effects": {"ex": -2}},
{"id": 367, "question": "I wouldn't oppose getting Cybernetic Implants (Robot Arms/Legs, Chips, etc.)", "effects": {"ex": -2}},
{"id": 368, "question": "Robots and A.I are inherently superior to us puny humans.", "effects": {"ex": -2}},
{"id": 369, "question": "It is inevitable that humans will be replaced by machines.", "effects": {"ex": -2}},
{"id": 370, "question": "No A.I will be able to outmatch humanity.", "effects": {"ex": -2}},
{"id": 371, "question": "When people have already suffered for technology to be developed, we should use that technology", "effects": {"ex": -2}},
{"id": 372, "question": "We should put effort into getting a person on Mars in the near future", "effects": {"ex": -2}},
{"id": 373, "question": "Space is the last frontier.", "effects": {"ex": -2}},
  
//Technological Transhumanism - Transhumanism
{"id": 374, "question": "Getting past physical limitations through technology would be beneficial to mankind.", "effects": {"ey": 2}},
{"id": 375, "question": "Transhumanism will be inevitable in the near future, in most nations.", "effects": {"ey": 2}},
{"id": 376, "question": "People are overly worrying about physical human modifications nowadays.", "effects": {"ey": 2}}, 
//Technological Transhumanism - Primitivism
{"id": 377, "question": "We must go back to a basic way of life without modern conveniences.", "effects": {"ey": -2}},
{"id": 378, "question": "Technology that improves mental and physical capabilities shouldn't be used, in any political system.", "effects": {"ey": -2}},
{"id": 379, "question": "The risks of transhumanism overweighs the benefits.", "effects": {"ey": -2}},
{"id": 380, "question": "Transhumanism is not required in any country within the next 20 years.", "effects": {"ey": -2}},

//Law System - Civil Law
{"id": 381, "question": "Law principles should be codified into a referable system.", "effects": {"fx": 2}},
{"id": 382, "question": "If a law system exists, lawmakers and legal experts should hold more influence than judges.", "effects": {"fx": 2}},
{"id": 383, "question": "It is very important to maintain law and order.", "effects": {"fx": 2}}, 
//Law System - Common Law
{"id": 384, "question": "Courts should reference to other judicial decisions.", "effects": {"fx": -2}},
{"id": 385, "question": "If judges and legislators exist, judges should hold more power than legislators.", "effects": {"fx": -2}},
{"id": 386, "question": "If a decision cannot be made in courts, relevant cases in the past should be referenced.", "effects": {"fx": -2}},
{"id": 387, "question": "Unusual cases cannot be decided with written law.", "effects": {"fx": -2}},

//Law Focus - Punitive
{"id": 388, "question": "A rehabilitative system is unjust.", "effects": {"fy": 2}},
{"id": 389, "question": "Punishment should be valued, more than that of rehabilitation.", "effects": {"fy": 2}},
{"id": 390, "question": "It's a waste of time trying to rehabilitate some criminals.", "effects": {"fy": 2}},
{"id": 391, "question": "I support capital punishment.", "effects": {"fy": 2}},  
//Law Focus - Rehabilitive
{"id": 392, "question": "Everybody deserves a second chance.", "effects": {"fy": -2}},

//Cultural Hierarchy - Equality
{"id": 393, "question": "Everyone, and everything, is created equal.", "effects": {"gx": -2}},
{"id": 394, "question": "People, as humans, regardless of their actions, are always equal.", "effects": {"gx": -2}},
{"id": 395, "question": "Equality of outcome is important", "effects": {"gx": -2}},
{"id": 396, "question": "A system of equal outcomes should be established.", "effects": {"gx": -2}},
{"id": 397, "question": "People should have equal opportunity to succeed", "effects": {"gx": -2}},
{"id": 398, "question": "People should be treated equally regardless of their groups, characteristics, sexuality, or culture.", "effects": {"gx": -2}},
//Cultural Hierarchy - Hierarchy
{"id": 399, "question": "Even though equal opportunities can lead to equal outcomes, society should still focus on equal opportunities, and not equal outcomes.", "effects": {"gx": -2}},
{"id": 400, "question": "Hierarchies will inevitably be formed in every society, at any time.", "effects": {"gx": -2}},
{"id": 401, "question": "Any well-functioning society requries a hierarchy.", "effects": {"gx": -2}},
{"id": 402, "question": "A hierarchical state is best.", "effects": {"gx": -2}},
{"id": 403, "question": "In a civilised society, one must always have people above to be obeyed and people below to be commanded.", "effects": {"gx": -2}},
{"id": 404, "question": "Some groups of people should be discriminated against.", "effects": {"gx": -2}},
{"id": 405, "question": "We should either assimilate or kill anyone who's not in my group.", "effects": {"gx": -2}},

//Cultural Assimilation - Monocultural
{"id": 406, "question": "If we accept migrants into our borders, the migrants should be expected to assimilate into our culture.", "effects": {"gy": 2}},
{"id": 407, "question": "Multiculturalism is unrealistic.", "effects": {"gy": 2}},
{"id": 408, "question": "Some cultures are inherently suprerior to other cultures.", "effects": {"gy": 2}}, 
{"id": 409, "question": "Only my culture should exist, and all other cultures are inferior and spooks.", "effects": {"gy": 2}}, 
{"id": 410, "question": "All cultures that aren't mine should not interact with me, or face eradication.", "effects": {"gy": 2}}, 
{"id": 411, "question": "The best way of maintaining peace among a people is by letting all ethnic, political, cultural, religious, or any other groups have their own Country.", "effects": {"gy": 2}}, 
//Cultural Assimilation - Multicultural
{"id": 412, "question": "My nation should be more diverse.", "effects": {"gy": -2}},
{"id": 413, "question": "No cultures are superior to others.","effects": {"gy": -2}},
{"id": 414, "question": "I enjoy some foreign cultures","effects": {"gy": -2}},
{"id": 415, "question": "We should be more accepting to other cultures","effects": {"gy": -2}},
{"id": 416, "question": "I like to try food from other cultures and nations in resteraunts.","effects": {"gy": -2}},
{"id": 417, "question": "Our culture would be better with other cultures mixed in more","effects": {"gy": -2}},
{"id": 418, "question": "Monoculturalism is disastrous for society.", "effects": {"gy": -2}},
{"id": 419, "question": "National cultures are important to protect", "effects": {"gy": -2}},
{"id": 420, "question": "Race and ethnicity should be unimportant for everyone.", "effects": {"gy": -2}},
{"id": 421, "question": "Everybody should speak at least two languages", "effects": {"gy": -2}},
{"id": 422, "question": "All societies are a blend of cultures", "effects": {"gy": -2}},

//Procedural Compromize - Compromize 
{"id": 423, "question": "Compromises should be made in order to suit the needs of most people.", "effects": {"hx": -2}},
{"id": 424, "question": "Compromizing can avoid unnecessary conflict.", "effects": {"hx": -2}},
{"id": 425, "question": "Adopting radical ideas isn't possible unless compromizes are made.", "effects": {"hx": -2}},
  
//Procedural Transition - Transitional
{"id": 426, "question": "A transitional state should be made.", "effects": {"hy": 2}},  
//Procedural Transition - Direct
{"id": 427, "question": "My ideology should be established as quick as possible.", "effects": {"hy": -2}},
{"id": 428, "question": "My political ideals can be acheived within 10 years.", "effects": {"hy": -2}},
{"id": 429, "question": "Nobody but me can adequately represent my views", "effects": {"hy": -2}},
  
//Political Extremism - Radical
{"id": 430, "question": "My ideology is sometimes considered 'extreme'.", "effects": {"ix": 2}},
{"id": 431, "question": "Violence and Revolutions are required in order to establish my ideology.", "effects": {"ix": 2}},
{"id": 432, "question": "The current mainstream societal attitudes are problematic.", "effects": {"ix": 2}},
{"id": 433, "question": "My political views are very different from the current status quo.", "effects": {"ix": 2}},

//Political Engagement - Apolitical
{"id": 434, "question": "Politics is boring to me.", "effects": {"iy": -2}},
{"id": 435, "question": "Nearly all politicians are evil and problematic, no matter what their political ideals are.", "effects": {"iy": -2}},
{"id": 436, "question": "Politics should be avoided in daily life.", "effects": {"iy": -2}},
//Political Engagement - Politicized
{"id": 437, "question": "Politics is very important for society, and shouldn't be ignored.", "effects": {"iy": 2}},
  
//Collectivization
{"id": 438, "question": "An Individual by themself is useless.", "effects": {"ja": -2}},
{"id": 439, "question": "Most things can only be accomplished through a group.", "effects": {"ja": -2}},
{"id": 440, "question": "I'd rather work in a group than by myself.", "effects": {"ja": -2}},
{"id": 441, "question": "An Individual can do much more by themself, than being restricted in a group.", "effects": {"ja": 2}},
{"id": 442, "question": "We should all think alike.", "effects": {"ja": -2}},
{"id": 443, "question": "Humans are united by nature, and should not act alone.", "effects": {"ja": -2}},
{"id": 444, "question": "If the current career system is being used, a person's personal and work life should stay seperate.", "effects": {"ja": 2}},
{"id": 445, "question": "It is the objective of every person to be as useful as possible.", "effects": {"ja": -2}},
{"id": 446, "question": "People's actions should benefit the collective in someway.", "effects": {"ja": -2}},
{"id": 447, "question": "Being self-sufficient (as a person) is a positive trait.", "effects": {"ja": 2}},
{"id": 448, "question": "Egoism is not necessarily bad.", "effects": {"ja": 2}},
{"id": 449, "question": "The Individual has no obligation to contribute to the Collective.", "effects": {"ja": 2}},
{"id": 450, "question": "Every Individual is just another piece of the Collective", "effects": {"ja": -2}},
{"id": 451, "question": "The Individual has no power compared to the Collective.", "effects": {"ja": -2}},
{"id": 452, "question": "Individual choices are always right, and should not be influenced by the Collective.", "effects": {"ja": 2}},
{"id": 453, "question": "People should care more about themselves than anyone else.", "effects": {"ja": 2}},
{"id": 454, "question": "If I could, I would seperate myself from the rest of society.", "effects": {"ja": 2}},
{"id": 455, "question": "It is natural for humans to be destructive.", "effects": {"ja": 2}},
{"id": 456, "question": "The fact is people are destructive, and stopping that is a waste of time and money.", "effects": {"ja": 2}},

//Revolution
{"id": 457, "question": "Changing the status quo using violent methods is mostly unhelpful.", "effects": {"jb": 2}},
{"id": 458, "question": "Pacifism is generally unrealistic when protesting a government.", "effects": {"jb": -2}},
{"id": 459, "question": "Countries that violate human rights should be toppled", "effects": {"jb": -2}},
{"id": 460, "question": "Countries that do not serve our interests should be toppled", "effects": {"jb": -2}},
{"id": 461, "question": "I don't see anything wrong with theft/stealing.", "effects": {"jb": -2}},

//Idealism
{"id": 462, "question": "Idealists are mostly unrealistic.", "effects": {"jc": 2}},
{"id": 463, "question": "We should not ignore ideologies that seem radical, but has a chance of success.", "effects": {"jc": -2}},
{"id": 464, "question": "We should be more optimistic towards a variety of different ideas.", "effects": {"jc": -2}},

//Consequence
{"id": 465, "question": "An eye for eye and a tooth for tooth.", "effects": {"jd": 2}},
{"id": 466, "question": "We should judge an action based on its consequences.", "effects": {"jd": 2}},
{"id": 467, "question": "An action should be seen as right or wrong through a set of rules and principles.", "effects": {"jd": -2}},
{"id": 468, "question": "Intention is more important than consequence when judging an action.", "effects": {"jd": -2}}, 
 
];
